### ISSUE TITLE
I can't click the buttons on the app.omniibo.com site

### ISSUE THREAD

**Issue by Greybuster** [Swordstone86/omniibo#4]
They seem to be disabled? 

I'm using the newest Chrome Version 105.0.5195.127

**Comment by Branhernan** [comment]
> They seem to be disabled?
> 
> I'm using the newest Chrome Version 105.0.5195.127

Ran into the same issue, the buttons seems to have been manually disabled for some reason. For the time being, if you pull up the link on the Wayback Machine you can use a snapshot from Sep 16th to use it that way.

(Here's the link: [https://web.archive.org/web/20220916212316/https://app.omniibo.com/](url))

**Comment by Greybuster** [comment]
Thanks for the update. It works again.
